"""Nuke `.nk` curves-knob cache for fast re-import.

The Python API's per-knot ``Shape.append(AnimControlPoint)`` is what
makes ``build_roto`` slow on dense clips — nearly all of an 82s build
on a 323-object UHD plate is spent inside per-knot append (confirmed
on skylab 2026-10-07 via ``benchmarks/nuke_bottleneck.py``). Nuke's
C++ parser via ``nuke.rotopaint.Shape._curves.fromScript()`` can
reload the same roto in 0.44s — a **188× speedup**.

This module caches the result of the first build:
    cache = NukeImportCache(doc_path, model_version=...)
    text = cache.get()
    if text:
        roto["curves"].fromScript(text)
    else:
        roto = build_roto(doc, ...)        # slow path, once
        cache.put(roto["curves"].toScript())

The cache key is a hash of the input JSON path, its mtime, and the
build-parameter triple (mode, curve_type, undersample_tolerance). A
different mode or tolerance invalidates automatically.

Cache location: ``$XDG_CACHE_HOME/rotobot_nuke/`` (default
``~/.cache/rotobot_nuke/``). Each cached entry is a tiny .txt file
holding the ``curves`` knob text (~2–20 KB per clip, well under 1 MB
even for the largest observed real plate).

Not thread-safe — one Nuke session should write cache entries, but
reads are safe to race.
"""

from __future__ import annotations

import hashlib
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple


@dataclass(frozen=True)
class CacheKey:
    doc_path: str
    doc_mtime_ns: int
    mode: str
    curve_type: str
    undersample_tolerance: Optional[float]

    def digest(self) -> str:
        h = hashlib.sha256()
        h.update(str(self.doc_path).encode("utf-8"))
        h.update(str(self.doc_mtime_ns).encode("utf-8"))
        h.update(self.mode.encode("utf-8"))
        h.update(self.curve_type.encode("utf-8"))
        tol = (
            "none"
            if self.undersample_tolerance is None
            else f"{self.undersample_tolerance:.6g}"
        )
        h.update(tol.encode("utf-8"))
        return h.hexdigest()[:16]


def _cache_root() -> Path:
    base = os.environ.get("XDG_CACHE_HOME") or os.path.expanduser("~/.cache")
    root = Path(base) / "rotobot_nuke"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _entry_path(key: CacheKey) -> Path:
    stem = Path(key.doc_path).stem
    # Trim long autogenerated stems to keep filenames workable.
    if len(stem) > 60:
        stem = stem[:60]
    return _cache_root() / f"{stem}.{key.digest()}.curves.txt"


def make_key(
    doc_path: str,
    *,
    mode: str = "legacy",
    curve_type: str = "bspline",
    undersample_tolerance: Optional[float] = None,
) -> CacheKey:
    """Construct a ``CacheKey`` from a doc path + build parameters.

    Reads the file's mtime so a re-written JSON invalidates its cache
    entry on next import.
    """
    try:
        mtime_ns = os.stat(doc_path).st_mtime_ns
    except OSError:
        mtime_ns = 0
    return CacheKey(
        doc_path=str(doc_path),
        doc_mtime_ns=mtime_ns,
        mode=mode,
        curve_type=curve_type,
        undersample_tolerance=undersample_tolerance,
    )


def get(key: CacheKey) -> Optional[str]:
    """Return the cached curves text for ``key``, or ``None`` if absent."""
    p = _entry_path(key)
    try:
        return p.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError:
        return None


def put(key: CacheKey, text: str) -> Path:
    """Atomically write ``text`` under ``key``. Returns the written path."""
    p = _entry_path(key)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=p.parent, prefix=p.name + ".", suffix=".tmp",
        delete=False,
    ) as f:
        f.write(text)
        tmp = Path(f.name)
    tmp.replace(p)
    return p


def invalidate(key: CacheKey) -> bool:
    """Remove the cache entry for ``key`` if present. Returns True if removed."""
    p = _entry_path(key)
    try:
        p.unlink()
        return True
    except FileNotFoundError:
        return False
    except OSError:
        return False


def cache_stats() -> Tuple[int, int]:
    """``(entry_count, total_bytes)`` — for ops / debugging."""
    root = _cache_root()
    n = 0
    total = 0
    for p in root.glob("*.curves.txt"):
        n += 1
        try:
            total += p.stat().st_size
        except OSError:
            pass
    return (n, total)
